-- Create careGivers table
CREATE TABLE public."careGivers" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    fname TEXT,
    lname TEXT,
    "carePlans" INTEGER,
    nid TEXT,
    address TEXT,
    moo TEXT,
    subdist TEXT,
    dist TEXT,
    prov TEXT,
    patients INTEGER,
    img TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create patients table
CREATE TABLE public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    fname TEXT,
    lname TEXT,
    age INTEGER,
    nid TEXT,
    adl INTEGER,
    "ltcGroup" TEXT,
    frequency TEXT,
    weight REAL,
    height REAL,
    bmi REAL,
    waist REAL,
    address TEXT,
    moo TEXT,
    subdist TEXT,
    dist TEXT,
    prov TEXT,
    "primaryCareGiver" TEXT,
    "careGiverId" BIGINT REFERENCES public."careGivers"(id) ON DELETE SET NULL,
    img TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create drugs table
CREATE TABLE public.drugs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    dosage TEXT,
    barcode TEXT,
    "colorTxt" TEXT,
    "colorHex" TEXT,
    "shapeTxt" TEXT,
    "shapeType" TEXT,
    "realImg" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up Row Level Security (RLS) - Optional but recommended for Supabase
ALTER TABLE public."careGivers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drugs ENABLE ROW LEVEL SECURITY;

-- Create policies to allow read/write access (Modify as needed for security)
CREATE POLICY "Enable read access for all users" ON public."careGivers" FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."careGivers" USING (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON public.patients FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.patients USING (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON public.drugs FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.drugs USING (auth.role() = 'authenticated');
